name: Frontend build

on:
  watch:
    types: [started]

jobs:
  buildx:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker buildx --platform linux/amd64,linux/arm/v7 ./frontend/. \
        --tag emilsallem/rowa-frontend:master
      - name: Login to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the latest Docker image
        run: docker push emilsallem/rowa-frontend:master
